# Generated by Django 3.1.3 on 2020-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.TextField(default='Blad przy wczytywaniu autora badz jest on pusty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(default='chuj wie kiedy wstawiles'),
        ),
        migrations.AlterField(
            model_name='post',
            name='opis',
            field=models.TextField(default='Blad! Opis pusty lub nie wczytany'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.TextField(default='Blad! Tytul pusty lub nie wczytany'),
        ),
    ]
