# Generated by Django 3.1.3 on 2020-11-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0002_auto_20201118_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(default='Blad! Tytul pusty lub nie wczytany', max_length=60),
        ),
    ]
