# Generated by Django 3.1.3 on 2020-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0006_auto_20201119_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='opis',
            field=models.CharField(blank=True, default='Blad! Opis pusty lub nie wczytany', max_length=800, null=True),
        ),
    ]
