# Generated by Django 3.1.3 on 2020-11-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0007_auto_20201119_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='C:\\Users\\ASUS\\Desktop\\bk_django\\projekt\\src\\meet_me\\static/img/logo.png', upload_to=''),
        ),
    ]
