# Generated by Django 3.1.3 on 2020-11-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0008_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.TextField(default='Błędne dane bądź ich brak'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(default='Błędne dane bądź ich brak'),
        ),
        migrations.AlterField(
            model_name='post',
            name='opis',
            field=models.CharField(blank=True, default='Błędne dane bądź ich brak', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(default='Błędne dane bądź ich brak', max_length=60),
        ),
    ]
