# Generated by Django 3.1.3 on 2020-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0012_auto_20201124_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
