# Generated by Django 3.1.3 on 2020-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0015_auto_20201128_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
