# Generated by Django 3.1.3 on 2020-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0019_auto_20201129_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
