# Generated by Django 3.1.3 on 2020-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0022_auto_20201129_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb',
            field=models.URLField(max_length=100),
        ),
    ]
