# Generated by Django 3.1.3 on 2020-11-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0024_auto_20201129_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
