# Generated by Django 3.1.3 on 2020-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0025_auto_20201129_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb',
            field=models.URLField(max_length=100),
        ),
    ]
