# Generated by Django 3.1.3 on 2020-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0027_auto_20201130_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
