# Generated by Django 3.1.3 on 2020-11-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0029_auto_20201130_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
