# Generated by Django 3.1.3 on 2020-12-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0030_auto_20201130_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
