# Generated by Django 3.1.3 on 2020-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0036_auto_20201205_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
