# Generated by Django 3.1.3 on 2020-12-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0038_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
