# Generated by Django 3.1.3 on 2020-12-06 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posty', '0039_auto_20201206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
