# Generated by Django 3.1.3 on 2020-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0041_userprofile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat_long',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
