# Generated by Django 3.1.3 on 2020-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0042_auto_20201208_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lat_long',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
