# Generated by Django 3.1.3 on 2020-12-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0045_remove_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
