# Generated by Django 3.1.3 on 2020-12-18 16:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0048_auto_20201218_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=70, size=[900, 700], upload_to='gallery/'),
        ),
    ]
