# Generated by Django 3.1.3 on 2020-12-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0051_auto_20201218_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
