# Generated by Django 3.1.3 on 2020-12-18 17:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0052_auto_20201218_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=40, size=[900, 700], upload_to='gallery/'),
        ),
    ]
