# Generated by Django 3.1.3 on 2020-12-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0053_auto_20201218_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lng',
        ),
    ]
