# Generated by Django 3.1.3 on 2020-12-18 19:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0054_auto_20201218_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=40, size=[700, 700], upload_to='gallery/'),
        ),
    ]
