# Generated by Django 3.1.3 on 2020-12-22 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0056_auto_20201222_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fb',
            field=models.URLField(blank=True, default='https://fb.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ig',
            field=models.URLField(blank=True, default='https://fb.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tt',
            field=models.URLField(blank=True, default='https://fb.com', max_length=100),
            preserve_default=False,
        ),
    ]
