# Generated by Django 3.1.3 on 2020-12-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0057_auto_20201222_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
