# Generated by Django 3.1.3 on 2021-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0058_auto_20201225_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ig',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
