# Generated by Django 3.1.3 on 2021-01-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0060_remove_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
