# Generated by Django 3.1.3 on 2021-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0061_auto_20210102_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
